#!/usr/bin/env bash

# MIT License
#
# Copyright (c) 2020 veleth
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# help message
help() {
    printf "\x1B[93mdisfetch is a CLI system information tool written in bash\x1B[0m

    \x1B[1msyntax\x1B[0m:
    \tdisfetch \x1B[92m[options]\x1B[0m
    \x1B[1moptions\x1B[0m:
    \t\x1B[92m-h, --help\x1B[0m                    \x1B[93mprints this message\x1B[0m
    \t\x1B[92m-l, --logo\x1B[0m                    \x1B[93msets distro logo to print\x1B[0m
    \t\x1B[92m-m, --mono, --monochrome\x1B[0m      \x1B[93menables monochrome mode\x1B[0m
    \n"
}

# parse arguments
while [ -n "$1" ] && [ "$1" != -- ]; do
    case $1 in
        -h|--help)
            help; exit 0
            ;;
        -l|--logo)
            OS_LOGO=$2
            ;;
        -m|--mono|--monochrome)
            MONO=1
            ;;
    esac
    shift
done

###########################################
# global stuff needed everywhere          #
###########################################
# info array
INFO=()

if [ -e $MONO ]; then
    # all colors
    declare -A colors
    colors[b]="\x1B[34m$zz"  # blue
    colors[bb]="\x1B[94m$zz" # bright blue
    colors[c]="\x1B[36m"     # cyan
    colors[cc]="\x1B[96m$zz" # bright cyan
    colors[d]="\x1B[30m$zz"  # black
    colors[dd]="\x1B[90m$zz" # bright black
    colors[r]="\x1B[31m$zz"  # red
    colors[rr]="\x1B[91m$zz" # bright red
    colors[y]="\x1B[33m"     # yellow
    colors[yy]="\x1B[93m$zz" # bright yellow
    colors[m]="\x1B[35m"     # magenta
    colors[mm]="\x1B[95m$zz" # bright magenta
    colors[g]="\x1B[32m$zz"  # green
    colors[gg]="\x1B[92m$zz" # brignt green
    colors[xx]="\x1B[0m"     # reset
    colors[zz]="\x1B[1m"     # bold
    xx=${colors[xx]}
    zz=${colors[zz]}

    # system colors palette
    PALETTE=()
    PALETTE[0]="\x1B[37mW\x1B[97mE$xx "
    PALETTE[1]="\x1B[31mR\x1B[91mD$xx "
    PALETTE[2]="\x1B[32mG\x1B[92mN$xx "
    PALETTE[3]="\x1B[33mY\x1B[93mW$xx "
    PALETTE[4]="\x1B[34mB\x1B[94mE$xx "
    PALETTE[5]="\x1B[35mM\x1B[95mA$xx "
    PALETTE[6]="\x1B[36mC\x1B[96mN$xx "
    PALETTE[7]="\x1B[30mB\x1B[90mK$xx "
fi

###########################################
# getting needed information              #
###########################################

# getting hostname
if [ -f /etc/hostname ]; then
    HOSTNAME=$(cat /etc/hostname)
else
    HOSTNAME=$(uname -n)
fi

# getting OS name
if [ -f /etc/os-release ]; then
    # shellcheck source=/dev/null
    OS=$(. /etc/os-release && echo "$PRETTY_NAME" | tr '[:upper:]' '[:lower:]')
elif type lsb_release &>/dev/null; then
    OS=$(lsb_release -si | tr '[:upper:]' '[:lower:]')
else
    OS=$(uname -o | tr '[:upper:]' '[:lower:]')
fi

OS_LOGO=${OS_LOGO:-$OS}

# getting kernel version
# shellcheck disable=SC2034 # actually used in eval
[ "$OS" != haiku ] &&
    KERNEL=$(uname -r | tr '[:upper:]' '[:lower:]')

# getting kernel architecture
# shellcheck disable=SC2034 # actually used in eval
ARCH=$(uname -m | tr '[:upper:]' '[:lower:]')

# finding out if OS has uptime with prerrifying option
# or hardcoding prettified uptime
# shellcheck disable=SC2034 # actually used in eval
UPTIME="$(
    if [ "$(uptime -p 2>/dev/null)" ]; then
        uptime -p | sed 's/up //; s/,//g'
    elif [ -f /proc/uptime ]; then
        awk '{
            uptime = $1;
            if (uptime >= 604800) {
                if (uptime >= 1209600) {
                    printf "%s weeks ", int(uptime/604800);
                } else {
                    printf "1 week ";
                }
            }
            if (uptime >= 86400) {
                if (int((uptime%604800)/86400) > 0) {
                    if (int((uptime%604800)/86400) >= 2) {
                        printf "%s days ", int((uptime%604800)/86400);
                    } else {
                        printf "1 day ";
                    }
                }
            }
            if (uptime >= 3600) {
                if (int((uptime%86400)/3600) > 0) {
                    if (int((uptime%86400)/3600) >= 2) {
                        printf "%s hours ", int((uptime%86400)/3600);
                    } else {
                        printf "1 hour ";
                    }
                }
            }
            if (uptime >= 60) {
                if (int((uptime%3600)/60) > 0) {
                    if (int((uptime%3600)/60) >= 2) {
                        printf "%s minutes ", int((uptime%3600)/60);
                    } else {
                        printf "1 minute ";
                    }
                }
            }
            if (uptime >= 1 && 59 >= uptime) {
                if (int(uptime%60) > 0) {
                    if (int(uptime%60) >= 2) {
                        printf "%s seconds", int(uptime%60);
                    } else {
                        printf "1 second";
                    }
                }
            }
        }' /proc/uptime | xargs
    else
        uptime | cut -f1 -d "," | sed -E -e 's/^[^,]*up *//' \
            -e 's/, *[[:digit:]]* users.*//; s/min/minutes/' \
            -e 's/([[:digit:]]+):0?([[:digit:]]+)/\1 hours \2 minutes/' |
            xargs
    fi
)"

# getting current shell name
# shellcheck disable=SC2034 # actually used in eval
SHELL="$(basename "$SHELL")"

# getting DE and WM
# trying XDG_CURRENT_DESKTOP, if it doesn't exists, use DESKTOP_SESSION
# DESKTOP_SESSION is a full path so removing garbage
# shellcheck disable=SC2034 # actually used in eval
DESKTOP="$(
    if [ "$OS" != haiku ]; then
        de=$(echo "${XDG_CURRENT_DESKTOP:-$DESKTOP_SESSION}" | awk -F/ '{ print tolower($NF) }')
        if [ "$de" ] && echo "$de" | grep -Fq "none" || [ -z "$de" ]; then
            if [ "$WAYLAND_DISPLAY" ]; then
                wm="$(pgrep -lox "cage.*|cardboard|dwl|enlightenment|grefsen|
                        |hikari|kwin|mutter|river|sway|velox|wayfire|waymonad|
                        |weston|wio" | cut -d' ' -f2)"
            else
                # firstly getting root window id (WM) and then getting WM name, ignoring unimportant stuff
                # some WM do not have proper set atoms like _NET_SUPPORTING_WM_CHECK and _NET_WM_NAME
                # this workaround allows to detect such WM
                wm_id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK 2>/dev/null) &&
                wm="$(
                    xprop -id "${wm_id##* }" _NET_WM_NAME |
                            awk '{ print tolower($NF) }' | xargs ||
                        pgrep -lox "(2b|cat|d|fv|monster|so|tiny)wm|wmaker" |
                            cut -d' ' -f2
                )"
            fi
            echo "$wm"
        else
            echo "$de"
        fi
    fi
)"

###########################################
# defining distro logo and packages count #
###########################################
# note for nixos: display only current user installed packages
declare -A pm
pm[apk]='apk info | wc -l'
pm[dpkg]='dpkg -l | grep -c "^ii"'
pm[haiku]="pkgman search -ia | awk 'FNR > 2 { print }' | wc -l"
pm[nix]='nix-store -q --requisites ~/.nix-profile | wc -l'
pm[pacman]='pacman -Qq | wc -l'
pm[rpm]='rpm -qa | wc -l'
pm[zypper]='zypper se --installed-only | wc -l'
pm[slack]='ls /var/log/packages | wc -l'
pm[xbps]='xbps-query -l | wc -l'
pm[emerge]='ls -d /var/db/pkg/*/* | wc -l'

# shellcheck disable=SC2034 # actually used in eval
PACKAGES="$(
    eval "${pm["$(
        case $OS in
            alpine*|postm*) echo apk;;
            android*|astra*|*bian*|elementary*|*mint*|mx*|*ubuntu*|zorin*|kali*)
                echo dpkg;;
            arc*|artix*|endeavour*|manjaro*|garuda*|msys2*|parabola*)
                echo pacman;;
            fedora*|qubes*|cent*|redhat*) echo rpm;;
            gentoo*) echo emerge;;
            haiku*) echo haiku;;
            nixos*) echo nix;;
            slack*) echo slack;;
            void*) echo xbps;;
            opensuse*) echo zypper;;
        esac
    )"]}"
)"

# Bedrock linux workaround
if [ "$(brl 2>/dev/null)" ]; then
    OS_LOGO=bedrock
    OS=$(brl version | tr '[:upper:]' '[:lower:]')
fi

case $OS_LOGO in
    alpine*)
        motif=${colors[b]} # blue
        a=${colors[b]}     # blue
        LOGO[0]="     $a//AAAAAAAAAAA\\\\\\\\$xx   "
        LOGO[1]="    $a//$xx             $a\\\\\\\\$xx  "
        LOGO[2]="   $a//$xx    $zz<^>$xx        $a\\\\\\\\$xx "
        LOGO[3]="  $a//$xx   $zz,</$xx $zz\>,,$zz<^>,$xx  $a\\\\\\\\$xx"
        LOGO[4]="  $a\\\\\\\\$xx  $zz</$xx     $zz\>$xx   $zz\>$xx $a//$xx"
        LOGO[5]="   $a\\\\\\\\$xx$zz</$xx $zz/\\\\$xx    $zz\>$xx   $zz\\\\$xx$a//$xx "
        LOGO[6]="    $a\\\\\\\\$xx             $a//$xx  "
        LOGO[7]="     $a\\\\\\\\AAAAAAAAAAA//$xx   "
        ;;
    android*)
        motif=${colors[gg]} # bright green
        a=${colors[g]}$zz   # bold green
        LOGO[0]="     $a\..../$xx   "
        LOGO[1]="     ${a}d${xx}o${a}HH${xx}o${a}b$xx   "
        LOGO[2]="    $a''''''''$xx  "
        LOGO[3]="  $a.$xx ${a}GHHHHHHB$xx $a.$xx"
        LOGO[4]="  ${a}H$xx ${a}H######H$xx ${a}H$xx"
        LOGO[5]="  ${a}U$xx ${a}H######H$xx ${a}U$xx"
        LOGO[6]="    ${a}GHHHHHHB$xx  "
        LOGO[7]="      ${a}U$xx  ${a}U$xx    "
        ;;
    astra*)
        motif=${colors[bb]} # bright blue
        a=${colors[b]}$zz   # bold blue
        LOGO[0]="          $a.$xx        "
        LOGO[1]="        $a.'$xx.$a'.$xx      "
        LOGO[2]="  $a.....<$xx.$a:::$xx.$a>.....$xx"
        LOGO[3]="   $a'<$xx,'$a:::::::$xx',$a>'$xx "
        LOGO[4]="      $a<$xx,$a':::'$xx,$a>$xx    "
        LOGO[5]="     $a<$xx,$a'$xx,$a>^<$xx,$a'$xx,$a>$xx   "
        LOGO[6]="    $a<,>       <,>$xx  "
        LOGO[7]="   $a\`             \`$xx "
        ;;
    archbang*)
        motif=${colors[bb]}  # bright blue
        a=${colors[b]}       # blue
        b=${colors[ww]}$zz   # bright bold white
        LOGO[0]="        ${b}_____$xx    "
        LOGO[1]="        ${b}IG#LI$xx    "
        LOGO[2]="       $a/$xx${b}IMGBI$xx    "
        LOGO[3]="      $a/,$xx$b\\\\l1k/$xx    "
        LOGO[4]="     $a/,):$xx${b}IJl$xx$a,\\\\$xx   "
        LOGO[5]="    $a/,yC}$xx$b,=,${xx}${a}U,\\\\$xx  "
        LOGO[6]="   $a/,peZ$xx$b:BcK:$xx$a!,\\\\$xx "
        LOGO[7]="  $a/LL.\"\"\"$xx$b\`=\`$xx$a\".JJ\\\\$xx"
        ;;
    arco*)
        motif=${colors[b]}   # blue
        a=${colors[bb]}$zz   # bright bold blue
        LOGO[0]="         $a.$xx       "
        LOGO[1]="        $a/y\\\\$xx      "
        LOGO[2]="       $a/o^a\\\\$xx     "
        LOGO[3]="      $a/b/ \\\\b\\\\$xx    "
        LOGO[4]="     $a/b/   \\\\a\\\\$xx   "
        LOGO[5]="    $a/i/     \\\\g\\\\$xx  "
        LOGO[6]="   $a/z/  .___ \\\\w\\\\$xx "
        LOGO[7]="  $a/x/      \"TH\\\\c\\\\$xx"
        ;;
    arc*)
        motif=${colors[bb]}  # bright blue
        a=${colors[b]}       # blue
        b=${colors[c]}       # cyan
        LOGO[0]="         $a.$xx       "
        LOGO[1]="        $a/^\\\\$xx      "
        LOGO[2]="       $a/, ,\\\\$xx     "
        LOGO[3]="      $a/, $b${zz}v$xx$a ,\\\\$xx    "
        LOGO[4]="     $a/, $b$zz($xx $b$zz)$xx$a ,\\\\$xx   "
        LOGO[5]="    $a/,$xx $a>   $a<$xx $a,\\\\$xx  "
        LOGO[6]="   $a/.>$xx       $a<.\\\\$xx "
        LOGO[7]="  $a/>$xx           $a<\\\\$xx"
        ;;
    artix*)
        motif=${colors[b]}  # blue
        a=${colors[bb]}$zz  # bright bold blue
        b=${colors[b]}      # blue
        LOGO[0]="         $b.$xx       "
        LOGO[1]="        $b/$a#\\\\$xx      "
        LOGO[2]="       $b/,$a+,\\\\$xx     "
        LOGO[3]="        $b\`<${a}n,\\\\$xx    "
        LOGO[4]="     $a/$xx$b,    $b\`$a,\\\\$xx   "
        LOGO[5]="    $a/,hK$xx$b+>    $b,$xx  "
        LOGO[6]="   $a/.b$xx${b}>\`    $b<H$a.\\\\$xx "
        LOGO[7]="  $a/$xx$b>\`         $b\`<$a\\\\$xx"
        ;;
    bedrock*)
        motif=${colors[dd]} # bright black
        a=${colors[dd]}     # bright black
        b=${colors[w]}$zz   # bold white
        LOGO[0]="  $a=================$xx"
        LOGO[1]="  $a==$xx$b\\\\\ \\\\\\\\$xx$a==========$xx"
        LOGO[2]="  $a===$xx$b\\\\\ \\\\\\\\$xx$a=========$xx"
        LOGO[3]="  $a====$xx$b\\\\\ \`<<>>>$xx$a====$xx"
        LOGO[4]="  $a=====$xx$b\\\\\\\\$xx  ${a}__$xx  $b\\\\\\\\$xx$a==$xx"
        LOGO[5]="  $a======$xx$b\\\\\     //$xx$a==$xx"
        LOGO[6]="  $a=======$xx$b<<<<>>$xx$a====$xx"
        LOGO[7]="  $a=================$xx"
        ;;
    cent*)
        motif=${colors[yy]}  # bright yellow
        a=${colors[g]}       # green
        b=${colors[m]}       # magenta
        c=${colors[y]}       # yellow
        d=${colors[b]}       # blue
        LOGO[0]="        $c$zz/-\\\\$xx      "
        LOGO[1]="    ${a}F44N$xx $c$zz#$xx ${b}F11N$xx  "
        LOGO[2]="    ${a}L44X$xx $c$zz#$xx ${b}L11X$xx  "
        LOGO[3]="  $b$zz/_____$xx $xx~ $xx$d${zz}_____\\\\$xx"
        LOGO[4]="  $b$zz\\\\\"\"\"\"\"$xx $xx~ $xx$d${zz}\"\"\"\"\"/$xx"
        LOGO[5]="    ${d}F33N$xx $a$zz#$xx ${c}F22N$xx  "
        LOGO[6]="    ${d}L33X$xx $a$zz#$xx ${c}L22X$xx  "
        LOGO[7]="        $a$zz\-/$xx      "
        ;;
    debian*)
        motif=${colors[m]}  # magenta
        a=${colors[mm]}$zz  # bright bold magenta
        LOGO[0]="      $a,6tt6,$xx  "
        LOGO[1]="    $a,6$xx      ${a}6$xx "
        LOGO[2]="   ${a}6$xx    $a,6.$xx  ${a}6$xx"
        LOGO[3]="  $a'6$xx   ${a}6$xx    ${a}6'$xx"
        LOGO[4]="    ${a}6$xx   $a'6''$xx  "
        LOGO[5]="    $a'6$xx        "
        LOGO[6]="      $a'6$xx      "
        LOGO[7]="        $a'6.$xx   "
        ;;
    kali*)
        a=${colors[b]}
        LOGO[0]="  ${a}gggg$xx       "
        LOGO[1]="      ${a}888$xx    "
        LOGO[2]="  ${a}qqqq88888o$xx "
        LOGO[3]="     ${a}88    ee$xx"
        LOGO[4]="    ${a}88$xx       "
        LOGO[5]="     ${a}88$xx      "
        LOGO[6]="      ${a}888$xx    "
        LOGO[7]="         ${a}888$xx "
        ;;
    elementary*)
        motif=${colors[cc]} # bright cyan
        a=${colors[bb]}$zz  # bright bold blue
        LOGO[0]="        $a.,*,.$xx      "
        LOGO[1]="     $a.'$xx eeeee$xx $a'.$xx   "
        LOGO[2]="   $a.'$xx e$xx       e$xx $a'.$xx "
        LOGO[3]="  ${a}4${xx} ,e_________e$xx  ${a}L$xx"
        LOGO[4]="  ${a}V$xx  e\"\"\"\"\"\"\"\"\"\`$xx  ${a}7$xx"
        LOGO[5]="   $a\`,$xx e$xx       ,$xx $a,\`$xx "
        LOGO[6]="     $a\`, ${xx}eeeee$xx $a,\`$xx   "
        LOGO[7]="        $a\`'*'\`$xx      "
        ;;
    endeavour*)
        motif=${colors[bb]} # bright blue
        a=${colors[yy]}     # bright yellow
        b=${colors[mm]}     # bright magenta
        LOGO[0]="            $a,<\`$xx$b^<\\\\$xx     "
        LOGO[1]="          $a,<@$xx$b,<$xx${a}E\\\\$xx$b%%\\\\.$xx   "
        LOGO[2]="        $a,<@$xx$b,<$xx${a}ENDE\\\\$xx$b%%\\\\\\\\$xx  "
        LOGO[3]="      $a,<@$xx$b,<$xx${a}ENDEAVO\\\\$xx$b%%\\\\\\\\$xx "
        LOGO[4]="    $a,<@$xx$b,<$xx${a}ENDEAVOUR:D$xx$b%%\\\\\`$xx"
        LOGO[5]="   $a.__$xx$b<$xx${a}____#####_,P$xx$b%%%%%%D$xx"
        LOGO[6]="    $b<EFGJKX\`\`\`\`\`%%H%%_,P$xx "
        LOGO[7]="  $b<-------------\`\`\`$xx    "
        ;;
    fedora*)
        motif=${colors[b]} # blue
        a=${colors[b]}     # blue
        LOGO[0]="        $a.,*,.$xx      "
        LOGO[1]="     $a.'$xx   $zz,fff$xx$a'.$xx   "
        LOGO[2]="   $a.'$xx     ${zz}H$xx     $a'.$xx "
        LOGO[3]="  ${a}4$xx   $zz....H....$xx   ${a}L$xx"
        LOGO[4]="  ${a}h$xx   $zz\`\`\`\`H\`\`\`\`$xx   ${a}7$xx"
        LOGO[5]="  ${a}h$xx       ${zz}H$xx     $a,\`$xx "
        LOGO[6]="  ${a}c$xx    ${zz}fff'$xx   $a,\`$xx   "
        LOGO[7]="   $a\`zxjklfo'\`$xx      "
        ;;
    garuda*)
        motif=${colors[rr]} # bright red
        a=${colors[y]}      # yellow
        b=${colors[yy]}     # bright yellow
        c=${colors[rr]}$zz  # bold bright red
        LOGO[0]="          $b<< << >> << >>$xx   "
        LOGO[1]="        $b<<$xx     $a$zz<$xx        $c\\\\\\\\$xx "
        LOGO[2]="      $b<<$xx     $a$zz< I:::::::::$xx$c\\\\\\\\$xx"
        LOGO[3]="    $b<<$xx                     "
        LOGO[4]="  $b<<$xx    $a$zz<<$xx  $b<<  <<  <<  <<.$xx"
        LOGO[5]="   $c\\\\\\\\$xx    $a$zz\\\\\\  >>  >>  <<$xx $b>>$xx "
        LOGO[6]="    $c\\\\\\\\$xx             $a$zz<<$xx $b>>$xx   "
        LOGO[7]="     $c\\\\\\\\$xx $b\\\\\\ \\\\\\ // // //$xx     "
        ;;
    gentoo*)
        motif=${colors[mm]} # bright magenta
        a=${colors[m]}$zz   # bold magenta
        LOGO[0]="     $a.ggg.$xx     "
        LOGO[1]="   $a.dGGGGG\$b.$xx  "
        LOGO[2]="   $a\$GGG( )GGGb$xx "
        LOGO[3]="   ${a}Q\$GGGGGGGGG)$xx"
        LOGO[4]="     $a\'GGGGGGGP$xx "
        LOGO[5]="    ${a}dGGGGG\$P\'$xx  "
        LOGO[6]="  $a\$\$GGGG\$P$xx     "
        LOGO[7]="  $a\`qG\$\$P'$xx      "
        ;;
    haiku*)
        motif=${colors[yy]} # bright yellow
        a=${colors[bb]}$zz  # bold bright blue
        b=${colors[b]}$zz   # bold blue
        c=${colors[yy]}     # bright yellow
        LOGO[0]="                      $a, , m H$xx"
        LOGO[1]="           $a,$xx ${b}v$xx $a''\` L$xx ${b}V$xx      $a/$xx"
        LOGO[2]="  $a,      ?                 x$xx "
        LOGO[3]="   $a=_ _=-,$xx              $b<$xx    "
        LOGO[4]="           $a''K k s  \`\`$xx       "
        LOGO[5]="  ${c}H   H   / \   I  K  /  U  U$xx"
        LOGO[6]="  ${c}H H H  /=-=\  I  K++   U  U$xx"
        LOGO[7]="  ${c}H   H  A   A  I  K  \   UU$xx "
        ;;
    kubuntu*)
        motif=${colors[ww]} # bright white
        a=${colors[bb]}$zz  # bright bold blue
        LOGO[0]="       $a;\\\\.   ,/.$xx     "
        LOGO[1]="        ${a}B>'-'<:;  .>.$xx"
        LOGO[2]="   ${a}Y<.,        'GQ:'$xx "
        LOGO[3]="  ${a}__j//$xx              "
        LOGO[4]="  $a\"\"z\\\\\\\\$xx              "
        LOGO[5]="   ${a}L<'\`        ,JS:.$xx "
        LOGO[6]="        ${a}U>,_,<:;  '>'$xx"
        LOGO[7]="       $a;/'   \"\\\\'$xx     "
        ;;
    manjaro*)
        motif=${colors[g]} # green
        a=${colors[g]}     # green
        LOGO[0]="  ${a}[][][][][][]|$xx ${a}[][][]$xx"
        LOGO[1]="  ${a}[][][][][][]|$xx ${a}[][][]$xx"
        LOGO[2]="  ${a}[][][]\"\"\"\"\"\"\"$xx ${a}[][][]$xx"
        LOGO[3]="  ${a}[][][]$xx ${a}[][][]$xx ${a}[][][]$xx"
        LOGO[4]="  ${a}[][][]$xx ${a}[][][]$xx ${a}[][][]$xx"
        LOGO[5]="  ${a}[][][]$xx ${a}[][][]$xx ${a}[][][]$xx"
        LOGO[6]="  ${a}[][][]$xx ${a}[][][]$xx ${a}[][][]$xx"
        LOGO[7]="  ${a}[][][]$xx ${a}[][][]$xx ${a}[][][]$xx"
        ;;
    *mint*)
        motif=${colors[gg]} # bright green
        a=${colors[g]}$zz   # bold green
        LOGO[0]="  ${a}MM$xx   $a.*^*..*^*.$xx "
        LOGO[1]="  $a\$\$$xx  $a\$\$'$xx $a'\$\$'$xx $a'\$\$$xx"
        LOGO[2]="  $a\$\$$xx  $a\$\$$xx   $a\$\$$xx   $a\$\$$xx"
        LOGO[3]="  $a\$\$$xx  $a\$\$$xx   $a\$\$$xx   $a\$\$$xx"
        LOGO[4]="  $a\$\$$xx  $a\$\$$xx   $a\$\$$xx   $a\$\$$xx"
        LOGO[5]="  $a\$\$.$xx $a\`\`$xx   $a\`\`$xx  $a.\$\$$xx"
        LOGO[6]="  $a'Q\$\$\$\$\$\$\$\$\$\$\$\$Q'$xx"
        LOGO[7]="    $a\`\`\`\`\`\`\`\`\`\`\`\`$xx  "
        ;;
    msys2*)
        motif=${colors[yy]} # bright yellow
        a=${colors[m]}      # magenta
        b=${colors[yy]}     # bright yellow
        c=${colors[ww]}$zz  # bright bold white
        d=${colors[dd]}$zz  # bright bold black
        LOGO[0]="  $a/* * * * * * * * * * * */$xx"
        LOGO[1]="  $a//$xx    ${c}mWm$xx   ${c}c2c$xx ${b}___    $a//$xx"
        LOGO[2]="  $a//$xx   ${c}G   G Z  2$xx$b(__ \\\\$xx   $a//$xx"
        LOGO[3]="  $a//$xx  ${c}K     H$xx     $b/ _/$xx   $a//$xx"
        LOGO[4]="  $a//$xx  ${c}I     T$xx    $b(____)$xx  $a//$xx"
        LOGO[5]="  $a//$xx  ${c}A     v     P$xx      $a//$xx"
        LOGO[6]="  $a//$xx           ${d}S Y S$xx     $a//$xx"
        LOGO[7]="  $a/* * * * * * * * * * * */$xx"
        ;;
    mx*)
        motif=${colors[dd]} # bright black
        a=${colors[dd]}     # bright black
        LOGO[0]="         \\\\\\\\\\\\    //      "
        LOGO[1]="          \\\\\\\\\\\\  //       "
        LOGO[2]="           \\\\\\\\\\\\//        "
        LOGO[3]="            \\\\\\\\\\\\         "
        LOGO[4]="       *    /\\\\\\\\\\\\        "
        LOGO[5]="     <\`$a~$xx\`> // \\\\\\\\\\\\  *    "
        LOGO[6]="   <\`$a~~~~~$xx//   \\\\\\\\\\\\\`$a~$xx\`>  "
        LOGO[7]=" <\`$a~~~~~~$xx//$a~$xx\`> <\\\\\\\\\\\\$a~~~$xx\`>"
        ;;
    nixos*)
        motif=${colors[bb]} # bright blue
        a=${colors[b]}$zz   # bold blue
        b=${colors[cc]}     # bright cyan
        LOGO[0]="       $a\\\\\\\\$xx    $b\\\\\\\\  //$xx    "
        LOGO[1]="        $a\\\\\\\\$xx    $b\\\\\\\\//$xx     "
        LOGO[2]="    $a::::://====$xx$b\\\\\\\\$xx  $a//$xx  "
        LOGO[3]="       $b///$xx      $b\\\\\\\\$xx$a//$xx   "
        LOGO[4]="  $b\"\"\"\"//$xx$a\\\\\\\\$xx      $a///\"\"\"\"$xx"
        LOGO[5]="     $b//$xx  $a\\\\\\\\$xx$b====//:::::$xx "
        LOGO[6]="        $a//\\\\\\\\$xx    $b\\\\\\\\$xx     "
        LOGO[7]="       $a//  \\\\\\\\$xx    $b\\\\\\\\$xx    "
        ;;
    opensuse*)
        motif=${colors[gg]} # bright green
        a=${colors[g]}$zz   # bold green
        b=${colors[c]}      # cyan
        LOGO[0]="        $a.,*,.$xx      "
        LOGO[1]="     $a.'$xx  ${a}___$xx  $a'.$xx   "
        LOGO[2]="   $a.'--<'($xx${b}o$xx$a)\`,$xx  $a'.$xx "
        LOGO[3]="  ${a}4$xx     $b'_____$xx$a\`$xx   ${a}L$xx"
        LOGO[4]="  ${a}V$xx       ${a}___'$xx    ${a}7$xx"
        LOGO[5]="   $a\`,---->$xx      $a,\`$xx "
        LOGO[6]="     $a\`,$xx       $a,\`$xx   "
        LOGO[7]="        $a\`'*'\`$xx      "
        ;;
    parabola*)
        motif=${colors[bb]} # bright blue
        a=${colors[b]}$zz   # bold blue
        LOGO[0]="           ${a}_.__$xx   "
        LOGO[1]="     ${a}_.,;\"[ZAMW:+$xx "
        LOGO[2]="  $a,;\"\'\`       @#;:$xx"
        LOGO[3]="            $a.\$#;/$xx "
        LOGO[4]="           $a,/;/$xx   "
        LOGO[5]="          $a/;/$xx     "
        LOGO[6]="        $a;/>$xx       "
        LOGO[7]="      $a,/$xx          "
        ;;
    postmarket*)
        motif=${colors[gg]} # bright green
        a=${colors[g]}$zz   # bold green
        b=${colors[dd]}     # bright black
        LOGO[0]="         $a,/^\,$xx       "
        LOGO[1]="         $a\L$xx $a\\\\\\\\\\\\$xx      "
        LOGO[2]="       $a>_$xx    $a\\\\\\\\\\\\$xx     "
        LOGO[3]="      $a///$xx $b/$xx $b\\\\$xx $a\\\\\\\\\\\\$xx    "
        LOGO[4]="     $a///$xx $b/_$xx ${b}_\\\\$xx $a\KL$xx   "
        LOGO[5]="    $a///$xx        $a/$xx ${a}__$xx  "
        LOGO[6]="   $a///__\\\\$xx $a\_____/\\\\\\\\\\\\$xx "
        LOGO[7]="  $a/=====/$xx $a/=========\\\\$xx"
        ;;
    qubes*)
        motif=${colors[bb]} # bright blue
        a=${colors[b]}$zz   # bold blue
        LOGO[0]="       $a.<>.$xx     "
        LOGO[1]="    $a.<^>''<^>.$xx  "
        LOGO[2]="  $a<^><$xx      $a><^>$xx"
        LOGO[3]="  ${a}[:]$xx        ${a}[:]$xx"
        LOGO[4]="  ${a}[:]$xx        ${a}[:]$xx"
        LOGO[5]="  $a<:><$xx      $a><:>$xx"
        LOGO[6]="     $a<.>..<.>>$xx  "
        LOGO[7]="       $a\`<>\`$xx  $a</>$xx"
        ;;
    raspbian*)
        motif=${colors[rr]} # bright red
        a=${colors[r]}$zz   # bold red
        b=${colors[g]}      # green
        LOGO[0]="  ${b}_,_$xx       ${b}_,_$xx  "
        LOGO[1]="  $b\_$xx $b,\\\\$xx   $b/,$xx ${b}_/$xx  "
        LOGO[2]="    $b\\\\$xx $b,\Y/,$xx $b/$xx    "
        LOGO[3]="      $a($xx $a+$xx $a)      "
        LOGO[4]="   $a(+$xx $a($xx $a+$xx $a)$xx $a+)$xx   "
        LOGO[5]="  $a(+$xx $a(+)x(+)$xx $a+)$xx  "
        LOGO[6]="   $a(+$xx $a($xx $a+$xx $a)$xx $a+)$xx   "
        LOGO[7]="      $a($xx $a+$xx $a)$xx      "
        ;;
    redhat*)
        motif=${colors[rr]} # bright red
        a=${colors[r]}$zz   # red
        b=${colors[dd]}     # green
        LOGO[0]="          $a,,.___,,.$xx        "
        LOGO[1]="         $a<BwW5TZPdi\\\\$xx       "
        LOGO[2]="        $a<ZvCVQpnkGUy\\\\$xx      "
        LOGO[3]="   $a,<=\"Z$xx$b\" : _ _ _ : :$xx$a=__$xx   "
        LOGO[4]="  $a(/1Rc6Deh5cb1KsgJ6zKXD\`j$xx "
        LOGO[5]="   $a\`n,YC4kWzhusgyeZ4tkLy2Lk$xx"
        LOGO[6]="      $a\`ss ss_YWBPEmmxp__,\`$xx "
        LOGO[7]="             $a\`\'\"\"\'\" \`$xx      "
        ;;
    slack*)
        motif=${colors[bb]} # bright blue
        a=${colors[b]}      # blue
        LOGO[0]="     $a,sSSSSSs,$xx $a##$xx"
        LOGO[1]="    ${a}SS$xx       ${a}SS##$xx"
        LOGO[2]="    ${a}Ss$xx         $a\"\"$xx"
        LOGO[3]="     $a\`sSS,.$xx      "
        LOGO[4]="         $a\"SSs,$xx   "
        LOGO[5]="  $a##$xx         ${a}sS$xx  "
        LOGO[6]="  $a##Ss$xx       ${a}SS$xx  "
        LOGO[7]="  $a\"\"$xx $a\`sSSSSSs\`$xx   "
        ;;
    ubuntu*)
        motif=${colors[yy]} # bright yellow
        a=${colors[yy]}$zz  # bright bold yellow
        b=${colors[rr]}$zz  # bright bold red
        LOGO[0]="           $a.,C,.$xx  $b/**\\\\$xx"
        LOGO[1]="          ${a}B>'-'<X:$xx$b\\\\**/$xx"
        LOGO[2]="      $a.l,$xx        $a'GQ.$xx "
        LOGO[3]="  $b/**\\\\$xx $a//$xx             "
        LOGO[4]="  $b\\\\**/$xx $a\\\\\\\\$xx             "
        LOGO[5]="      ${a}\`I\`$xx        $a,JS'$xx "
        LOGO[6]="          ${a}U>,_,<N:$xx$b/**\\\\$xx"
        LOGO[7]="           $a\`'c'\`$xx  $b\\\\**/$xx"
        ;;
    void*)
        motif=${colors[g]} # green
        a=${colors[g]}$zz  # bold green
        b=${colors[gg]}$zz # bright bold green
        LOGO[0]="        $b.,C,.$xx      "
        LOGO[1]="         $b'-'<Z:.$xx   "
        LOGO[2]="   $a.J.$xx        $b\`SO.$xx "
        LOGO[3]="  ${a}4\$$a/$xx   $b/:+:\\\\$xx   $b\\\\@L$xx"
        LOGO[4]="  ${a}V#$a\\\\$xx   $b\:+:/$xx   $b/?7$xx"
        LOGO[5]="   $a\`NM,$xx        $b'v\`$xx "
        LOGO[6]="     $a\`:F>,_,$xx       "
        LOGO[7]="        $a\`'c'\`$xx      "
        ;;
    zorin*)
        motif=${colors[bb]}  # bright blue
        a=${colors[bb]}      # bright blue
        LOGO[0]="     $a//ZZZZZZZZZZZ\\\\\\\\$xx   "
        LOGO[1]="    $zz//\`\`\`\`\`\`\`\`\`\`\`\`\`\\\\\\\\$xx  "
        LOGO[2]="   $zz//......$xx$zz.     ...\\\\\\\\$xx "
        LOGO[3]="  $a//ZZZZZZZ$xx$zz>    <$xx${a}ZZZZ\\\\\\\\$xx"
        LOGO[4]="  $a\\\\\\\\ZZZZ$xx$zz>    <$xx${a}ZZZZZZZ//$xx"
        LOGO[5]="   $zz\\\\\\\\\`\`$xx$zz\`     \`\`\`\`\`\`\`//$xx "
        LOGO[6]="    $zz\\\\\\\\.............//$xx  "
        LOGO[7]="     $a\\\\\\\\ZZZZZZZZZZZ//$xx   "
        ;;
    *)
        motif=${colors[yy]} # bright yellow
        a=${colors[dd]}     # bright black
        b=${colors[y]}      # yellow
        LOGO[0]="        ${a}XXXX$xx      "
        LOGO[1]="       ${a}X$xx${zz}^$xx${a}XX$xx${zz}^$xx${a}X$xx     "
        LOGO[2]="       ${a}X$xx${b}<XX>$xx${a}X$xx     "
        LOGO[3]="     ${a}XX${xx}X${a}XXXX${xx}X${a}XX$xx   "
        LOGO[4]="    ${a}XX${xx}XXXXXXXX${a}XX$xx  "
        LOGO[5]="   ${a}XX${xx}XXXXXXXXXX${a}XX$xx "
        LOGO[6]="  ${b}I$xx${a}XXX${xx}XXXXXXXX${a}XXX$xx${b}I$xx"
        LOGO[7]="  ${b}IL>$xx${a}XX${xx}XXXXXX$xx${a}XX$xx${b}<JI$xx"
        ;;
esac

motif=$motif$zz

###########################################
# adding only existing layers to info     #
###########################################
INFO+=("$motif${USERNAME:-${USER:-${LOGNAME:-$(whoami)}}}$xx @ $motif$HOSTNAME$xx")
valign() {
    awk "BEGIN { while (i++ < 10 - length(\"$1\")) printf \" \" }"
}
for i in OS KERNEL ARCH UPTIME PACKAGES SHELL DESKTOP; do
    v="$(eval echo "\$$i")"
    [ "$v" ] &&
        INFO+=("${motif}$i:$xx$(valign "$i")$v")
done

###########################################
# yielding everything                     #
###########################################
# order: user@hostname, OS, kernel, arch, uptime, packages, shell, desktop
for i in $(seq 0 7); do
    # shellcheck disable=SC2059 # can't do anything about it
    printf "${LOGO[i]}  ${PALETTE[i]}| ${INFO[i]}\n"
done
